version: '3.3'
services: 
    db:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3307"
        volumes:
            - krtv_data:/var/www/mysql
volumes:
    krtv_data:
