server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: krtv-router
  datasource:
    url: jdbc:mysql://localhost:3306/krtv_router?createDatabaseIfNotExist=true
    username: root
    password: forge
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app: Update Router Service